ALL_COMMANDS = ['ac', 'activevc', 'addbadword', 'admincache', 'admins', 'afk', 'ai', 'antilink', 'approve', 'assistantjoin', 'audit', 'auth', 'authlist', 'authusers', 'autoend', 'backup', 'badmin', 'badwords', 'bal', 'ball', 'ban', 'banner', 'basket', 'bbcast', 'blacklistedchats', 'blchat', 'blchats', 'block', 'blocked', 'blockedusers', 'blusers', 'bored', 'bots', 'botschk', 'bug', 'cancel', 'captcha', 'channelplay', 'check', 'cimage', 'cleanup', 'clear', 'clearwarnings', 'cloop', 'cnext', 'coins', 'couple', 'cpause', 'cresume', 'cseek', 'cseekback', 'cshuffle', 'cskip', 'cute', 'daily', 'dare', 'dart', 'day', 'dbadmin', 'dban', 'decode', 'del', 'delalladmin', 'deleteall', 'demote', 'dice', 'domain', 'economy', 'encode', 'end', 'errorscan', 'extract', 'filter', 'filters', 'flood', 'font', 'football', 'fullpromote', 'gban', 'gbanlist', 'gbannedusers', 'get', 'getdraw', 'givelink', 'globalban', 'goodbye', 'groupdata', 'groupinfo', 'help', 'hide', 'history', 'id', 'imposter', 'info', 'ip', 'jackpot', 'kang', 'kick', 'kickme', 'lang', 'leaderboard', 'leaveall', 'leavegroup', 'level', 'levels', 'link', 'lock', 'logger', 'logs', 'loop', 'love', 'lyrics', 'maintenance', 'membership', 'meme', 'mmf', 'mode', 'mongochk', 'movie', 'mute', 'myhistory', 'mylevel', 'next', 'notes', 'packkang', 'pause', 'pin', 'ping', 'play', 'playback', 'player', 'playing', 'playmode', 'poll', 'post', 'profile', 'promote', 'protect', 'purge', 'purgefrom', 'pypi', 'q', 'qr', 'queue', 'quiz', 'raidmode', 'raidstatus', 'rank', 'reboot', 'recenterrors', 'refer', 'refresh', 'reload', 'remind', 'reminder', 'remindme', 'removebadword', 'removephoto', 'rep', 'repoaudit', 'report', 'reputation', 'resume', 'rmadmin', 'rmbg', 'rockpaperscissors', 'rps', 'rules', 'runtimeerrors', 'save', 'sban', 'seek', 'seekback', 'setbanner1', 'setbanner2', 'setdiscription', 'setfloodlimit', 'setgoodbye', 'setlang', 'setphoto', 'setprofilebanner', 'setprofilephoto', 'setrules', 'settings', 'settitle', 'setwarnlimit', 'setwelcome', 'sg', 'shop', 'short', 'shuffle', 'skip', 'slow', 'speed', 'speedtest', 'spt', 'spurge', 'staff', 'start', 'stats', 'stdl', 'stickerid', 'stop', 'store', 'string', 'tagall', 'tban', 'telegraph', 'tempadmin', 'tgm', 'tmute', 'top', 'toptracks', 'trivia', 'truth', 'tts', 'unapprove', 'unauth', 'unban', 'unblacklistchat', 'unblchat', 'unblock', 'ungban', 'unlock', 'unmute', 'unpin', 'unpinall', 'unshort', 'unwarn', 'upscale', 'user', 'userbotleave', 'userinfo', 'vcinfo', 'vcmembers', 'vip', 'voiceall', 'voices', 'vplay', 'vstart', 'waifu', 'wallet', 'warn', 'warnings', 'weather', 'weekly', 'whitelistchat', 'wish', 'word', 'wordle', 'write', 'zombies']

COMMAND_PAGE_SIZE = 32
COMMAND_PAGE_COUNT = (len(ALL_COMMANDS) + COMMAND_PAGE_SIZE - 1) // COMMAND_PAGE_SIZE

def command_page(page: int):
    page = max(1, min(int(page), COMMAND_PAGE_COUNT))
    start = (page - 1) * COMMAND_PAGE_SIZE
    return ALL_COMMANDS[start:start + COMMAND_PAGE_SIZE]
