"""Short, accurate "how to use" cards for every bot command.

Each entry:  command -> (what it does, usage, example, who can use it, tip)
Empty strings are simply not shown.  Keep every field to ONE short line so the
card stays clean on a phone screen (Telegram captions cap at 1024 characters).
"""

import config

EVERYONE = "Everyone"
EVERYONE_GRP = "Everyone · groups only"
ADMINS = "Group admins"
ADMINS_GRP = "Group admins · groups only"
PLAYER = "Admins & authorized users"
OWNER = "Bot owner"
BOT_ADMINS = "Bot admins"
PM = "Private chat"

_REPLY_USER = "Reply to a user's message"

# fmt: off
COMMAND_HELP = {
    # ───────────── music ─────────────
    "play":      ("Search a song and play it in the voice chat.", "/play <song name or link>", "/play Blinding Lights", EVERYONE_GRP, "You can also reply to an audio or video file with /play."),
    "vplay":     ("Play a video in the voice chat.", "/vplay <video name or link>", "/vplay Believer", EVERYONE_GRP, ""),
    "pause":     ("Pause the current track.", "/pause", "", PLAYER, ""),
    "resume":    ("Resume a paused track.", "/resume", "", PLAYER, ""),
    "skip":      ("Skip to the next track in the queue.", "/skip [track number]", "/skip 3", PLAYER, "Without a number it skips one track."),
    "next":      ("Skip to the next track in the queue.", "/next", "", PLAYER, "Same as /skip."),
    "stop":      ("Stop playback and clear the queue.", "/stop", "", PLAYER, ""),
    "end":       ("Stop playback and clear the queue.", "/end", "", PLAYER, ""),
    "queue":     ("Show the track that is playing and what is queued.", "/queue", "", EVERYONE_GRP, ""),
    "player":    ("Open the player card with control buttons.", "/player", "", EVERYONE_GRP, ""),
    "playing":   ("Show the track that is playing right now.", "/playing", "", EVERYONE_GRP, ""),
    "shuffle":   ("Shuffle the queued tracks.", "/shuffle", "", PLAYER, "Needs at least 2 queued tracks."),
    "seek":      ("Jump forward in the current track.", "/seek <seconds>", "/seek 30", PLAYER, ""),
    "seekback":  ("Jump backward in the current track.", "/seekback <seconds>", "/seekback 15", PLAYER, ""),
    "speed":     ("Change the playback speed.", "/speed", "", PLAYER, "Opens speed buttons. YouTube streams only."),
    "slow":      ("Change the playback speed.", "/slow", "", PLAYER, "Opens speed buttons. YouTube streams only."),
    "playback":  ("Change the playback speed.", "/playback", "", PLAYER, "Opens speed buttons. YouTube streams only."),
    "loop":      ("Repeat the current track.", "/loop enable | disable | 1-10", "/loop 3", PLAYER, "A number repeats the track that many times."),
    "playforce":  ("Play a song right now, replacing the current one.", "/playforce <song name or link>", "/playforce Believer", PLAYER, "Clears what is playing first."),
    "vplayforce": ("Play a video right now, replacing the current one.", "/vplayforce <video name or link>", "/vplayforce Believer", PLAYER, "Clears what is playing first."),
    "vend":       ("Stop playback and clear the queue.", "/vend", "", PLAYER, "Same as /end."),
    "cplay":      ("Play a song in the linked channel.", "/cplay <song name or link>", "/cplay Blinding Lights", EVERYONE_GRP, "Set the channel first with /channelplay."),
    "cvplay":     ("Play a video in the linked channel.", "/cvplay <video name or link>", "/cvplay Believer", EVERYONE_GRP, "Set the channel first with /channelplay."),
    "cplayforce": ("Play a song in the channel right now.", "/cplayforce <song name or link>", "", PLAYER, "Clears what is playing first."),
    "cvplayforce": ("Play a video in the channel right now.", "/cvplayforce <video name or link>", "", PLAYER, "Clears what is playing first."),
    "history":   ("Show your recent playback history.", "/history", "", EVERYONE, ""),
    "myhistory": ("Show your recent playback history.", "/myhistory", "", EVERYONE, ""),
    "toptracks": ("Show the most-played tracks.", "/toptracks", "", EVERYONE, ""),
    "top":       ("Show the most-played tracks.", "/top", "", EVERYONE, ""),
    "lyrics":    ("Find the lyrics of a song.", "/lyrics <song name>", "/lyrics Believer", EVERYONE, "Or reply to a message that contains the song name."),

    # ───────────── channel & voice chat ─────────────
    "cloop":       ("Repeat the current track in the linked channel.", "/cloop enable | disable | 1-10", "/cloop enable", PLAYER, "Channel-play version of /loop."),
    "cnext":       ("Skip to the next track in the linked channel.", "/cnext", "", PLAYER, "Channel-play version of /skip."),
    "cpause":      ("Pause playback in the linked channel.", "/cpause", "", PLAYER, ""),
    "cresume":     ("Resume playback in the linked channel.", "/cresume", "", PLAYER, ""),
    "cseek":       ("Jump forward in the channel track.", "/cseek <seconds>", "/cseek 30", PLAYER, ""),
    "cseekback":   ("Jump backward in the channel track.", "/cseekback <seconds>", "/cseekback 15", PLAYER, ""),
    "cshuffle":    ("Shuffle the channel queue.", "/cshuffle", "", PLAYER, ""),
    "cskip":       ("Skip the current channel track.", "/cskip [track number]", "/cskip 2", PLAYER, ""),
    "channelplay": ("Choose the channel where music is played.", "/channelplay linked | <channel id> | disable", "/channelplay linked", ADMINS_GRP, "'linked' uses the channel linked to this group."),
    "activevc":    ("List the voice chats that are active right now.", "/activevc", "", EVERYONE, ""),
    "ac":          ("Show how many voice chats are active.", "/ac", "", EVERYONE, ""),
    "vcinfo":      ("Show who is in the voice chat.", "/vcinfo", "", EVERYONE_GRP, ""),
    "vcmembers":   ("Show who is in the voice chat.", "/vcmembers", "", EVERYONE_GRP, ""),
    "vstart":      ("Start a voice chat in this group.", "/vstart", "", ADMINS_GRP, "The bot needs the 'manage voice chats' right."),
    "voiceall":    ("Choose a voice for text-to-speech.", "/voiceall", "", EVERYONE, "Browse voices, then use /tts."),
    "autoend":     ("Leave the voice chat automatically when nobody listens.", "/autoend enable | disable", "/autoend enable", BOT_ADMINS, ""),
    "playmode":    ("Choose how the bot searches and who can control the player.", "/playmode", "", ADMINS_GRP, "Opens settings buttons."),
    "mode":        ("Choose how the bot searches and who can control the player.", "/mode", "", ADMINS_GRP, "Opens settings buttons."),
    "assistantjoin": ("Invite the assistant account into this group.", "/assistantjoin", "", ADMINS_GRP, "Needed before voice-chat playback."),
    "userbotleave":  ("Make the assistant account leave this group.", "/userbotleave", "", ADMINS_GRP, ""),
    "leaveall":      ("Make the assistant account leave all groups.", ".leaveall", "", OWNER, "This one starts with a dot, not a slash."),

    # ───────────── AI ─────────────
    "ai":       ("Ask the AI anything.", "/ai <question>", "/ai Explain black holes simply", EVERYONE, "Or reply to a message with /ai."),
    "chat":     ("Chat with the AI.", "/chat <message>", "/chat Tell me a joke", EVERYONE, "Or reply to a message with /chat."),
    "cimage":   ("Create an AI image (VIP/VIP Pro; 3 per day).", "/cimage <prompt>", "/cimage cyberpunk ocean at night", EVERYONE, "VIP/VIP Pro only; 3 images per day. Owner is unlimited."),
    "upscale":  ("Enhance an image and double its size.", "/upscale", "", EVERYONE, "Reply to a photo first."),
    "getdraw":  ("Generate an AI image (VIP/VIP Pro; 3 per day).", "/getdraw <prompt>", "/getdraw a red dragon", EVERYONE, "VIP/VIP Pro only; 3 images per day. Or reply to a text message. Owner is unlimited."),
    "waifu":    ("Send a random waifu image.", "/waifu", "", EVERYONE, ""),
    "anime":    ("Search anime and get its card and episode list (VIP/VIP Pro).", "/anime <anime name>", "/anime Naruto", EVERYONE, "VIP/VIP Pro only. Also works as a reply. Alias: /asearch."),
    "asearch":  ("Search anime (VIP/VIP Pro only).", "/asearch <anime name>", "/asearch One Piece", EVERYONE, "Same as /anime."),
    "imposter": ("Turn the imposter word game on or off.", "/imposter enable | disable", "/imposter enable", ADMINS_GRP, ""),
    "tts":      ("Turn text into speech.", "/tts [voice] <text>", "/tts Hello everyone", EVERYONE, "Pick a voice with /voices."),
    "voices":   ("Pick a text-to-speech voice.", "/voices <text>", "/voices Good morning", EVERYONE, ""),
    "remember": ("Save something for the AI to remember in this chat.", "/remember <info>", "/remember We love jazz", EVERYONE, "Shared by everyone in the group."),
    "forget":   ("Erase what the AI remembers in this chat.", "/forget [exact text]", "", EVERYONE, "Without text it clears everything."),

    # ───────────── tools ─────────────
    "ping":      ("Check the bot's speed and system status.", "/ping", "", EVERYONE, ""),
    "stats":     ("Show bot and system statistics.", "/stats", "", EVERYONE, ""),
    "speedtest": ("Run a network speed test.", "/speedtest", "", EVERYONE, ""),
    "spt":       ("Run a network speed test.", "/spt", "", EVERYONE, "Shortcut for /speedtest."),
    "bug":       ("Report a bug to the developers.", "/bug <describe the problem>", "/bug /play gives an error", EVERYONE, ""),
    "lang":      ("Change the bot language.", "/lang", "", EVERYONE, "Opens language buttons."),
    "setlang":   ("Change the bot language.", "/setlang", "", EVERYONE, "Opens language buttons."),
    "font":      ("Turn text into stylish fonts.", "/font <text>", "/font Hello Aqua", EVERYONE, "Pick a style from the buttons."),
    "encode":    ("Convert text to hex.", "/encode <text>", "/encode Hello", EVERYONE, ""),
    "decode":    ("Convert hex back to text.", "/decode <hex>", "/decode 48656c6c6f", EVERYONE, ""),
    "short":     ("Shorten a long link.", "/short <link>", "/short https://example.com/very/long", EVERYONE, ""),
    "unshort":   ("Reveal where a short link goes.", "/unshort <short link>", "/unshort https://bit.ly/xyz", EVERYONE, ""),
    "qr":        ("Turn text or a link into a QR code.", "/qr <text or link>", "/qr https://example.com", EVERYONE, ""),
    "rmbg":      ("Remove the background from an image.", "/rmbg", "", EVERYONE, "Reply to a photo first."),
    "stickerid": ("Get the file ID of a sticker.", "/stickerid", "", EVERYONE, "Reply to a sticker first."),
    "stdl":      ("Download a sticker as an image.", "/stdl", "", EVERYONE, "Reply to a sticker first."),
    "kang":      ("Add a sticker or photo to your own sticker pack.", "/kang [emoji]", "/kang 😎", EVERYONE, "Reply to a sticker or photo first."),
    "packkang":  ("Copy a whole sticker pack into a new pack of yours.", "/packkang [pack name]", "/packkang My pack", EVERYONE, "Reply to a sticker first."),
    "string":    ("Generate a session string (Pyrogram, Pyrofork or Telethon).", "/string", "", PM, "Follow the on-screen steps. Never share your string."),
    "pypi":      ("Look up a Python package on PyPI.", "/pypi <package>", "/pypi requests", EVERYONE, ""),
    "domain":    ("Look up details of a domain.", "/domain <domain>", "/domain google.com", EVERYONE, ""),
    "ip":        ("Look up an IP address or domain.", "/ip <ip or domain>", "/ip 8.8.8.8", EVERYONE, ""),
    "check":     ("Check a username, link or value.", "/check <value>", "/check @username", EVERYONE, ""),
    "weather":   ("Show the weather of a city.", "/weather <city>", "/weather Pune", EVERYONE, ""),
    "telegraph": ("Upload a photo, video or text to Telegraph.", "/telegraph", "", EVERYONE, "Reply to the media or text first."),
    "tgm":       ("Upload a photo, video or text to Telegraph.", "/tgm", "", EVERYONE, "Reply to the media or text first."),
    "write":     ("Turn text into a handwritten-style image.", "/write <text>", "/write Dear diary", EVERYONE, "Or reply to a text message."),
    "extract":   ("Pull the audio or video out of a file.", "/extract audio | video", "/extract audio", EVERYONE, "Reply to a video first."),
    "remind":    ("Set a reminder.", "/remind <time> <text>", "/remind 10m Drink water", EVERYONE, "Time units: s, m, h, d. Maximum 7 days."),
    "reminder":  ("Set a reminder.", "/reminder <time> <text>", "/reminder 2h Call mom", EVERYONE, "Time units: s, m, h, d. Maximum 7 days."),
    "remindme":  ("Set a reminder.", "/remindme <time> <text>", "/remindme 1d Pay rent", EVERYONE, "Time units: s, m, h, d. Maximum 7 days."),
    "poll":      ("Create a poll.", "/poll <question> | <option 1> | <option 2>", "/poll Best day? | Friday | Sunday", EVERYONE, "Separate everything with the | symbol."),
    "day":       ("Find out which weekday a date falls on.", "/day <date>", "/day 15-08-1947", EVERYONE, ""),
    "sg":        ("Show a user's name and username history.", "/sg <user id or @username>", "/sg @username", EVERYONE, "Or reply to the user."),
    "q":         ("Turn a message into a quote sticker.", "/q", "", EVERYONE, "Reply to a message first."),
    "mmf":       ("Put meme text on an image.", "/mmf <top text>;<bottom text>", "/mmf When it works;When it doesn't", EVERYONE, "Reply to a photo first."),

    # ───────────── profile ─────────────
    "banner":           ("Show a bot banner.", "/banner [1 | 2]", "/banner 2", EVERYONE, ""),
    "setbanner1":       ("Save banner slot 1.", "/setbanner1", "", OWNER, "Reply to an image first."),
    "setbanner2":       ("Save banner slot 2.", "/setbanner2", "", OWNER, "Reply to an image first."),
    "id":               ("Show Telegram IDs.", "/id", "", EVERYONE, "Reply to a user or message to get their ID."),
    "info":             ("Show details about a user.", "/info [@username or id]", "/info @username", EVERYONE, "Or reply to the user."),
    "user":             ("Show member statistics of this chat.", "/user", "", ADMINS, ""),
    "userinfo":         ("Show details about a user.", "/userinfo", "", EVERYONE_GRP, "Reply to a user, or use it alone for yourself."),
    "groupinfo":        ("Show details about this group.", "/groupinfo", "", EVERYONE_GRP, ""),
    "level":            ("Show your level and XP in this group.", "/level", "", EVERYONE_GRP, ""),
    "mylevel":          ("Show your level and XP in this group.", "/mylevel", "", EVERYONE_GRP, ""),
    "rank":             ("Show your level and XP in this group.", "/rank", "", EVERYONE_GRP, ""),
    "levels":           ("Show the level leaderboard of this group.", "/levels", "", EVERYONE_GRP, ""),
    "leaderboard":      ("Show the level leaderboard of this group.", "/leaderboard", "", EVERYONE_GRP, ""),
    "ranking":          ("Show group rankings: Economy, Songs Played and XP.", "/ranking [economy | songs | xp]", "/ranking songs", EVERYONE_GRP, "Tap the tabs under the list to switch."),
    "rankings":         ("Show group rankings: Economy, Songs Played and XP.", "/rankings", "", EVERYONE_GRP, "Same as /ranking."),
    "rep":              ("Give reputation to a member.", "/rep", "", EVERYONE_GRP, "Reply to the member first."),
    "reputation":       ("Give reputation to a member.", "/reputation", "", EVERYONE_GRP, "Reply to the member first."),
    "afk":              ("Mark yourself away.", "/afk [reason]", "/afk Back in an hour", EVERYONE_GRP, "The bot tells people who mention you."),

    # ───────────── economy ─────────────
    "balance": ("Show your coin balance.", "/balance", "", EVERYONE_GRP, ""),
    "bal":     ("Show your coin balance.", "/bal", "", EVERYONE_GRP, ""),
    "daily":   ("Claim your daily coins.", "/daily", "", EVERYONE_GRP, "Once every 24 hours."),
    "give":    ("Send coins to another member.", "/give <amount>", "/give 250", EVERYONE_GRP, "Reply to the member first."),
    "toprich": ("Show the richest members.", "/toprich", "", EVERYONE_GRP, ""),
    "rich":    ("Show the richest members.", "/rich", "", EVERYONE_GRP, ""),
    "jackpot": ("Spin the jackpot slot machine.", "/jackpot", "", EVERYONE, ""),
    "vip":     ("Show VIP plans and perks.", "/vip", "", EVERYONE, ""),

    # ───────────── fun & games ─────────────
    "rps":               ("Play Rock, Paper, Scissors.", "/rps", "", EVERYONE, "Pick with the buttons."),
    "rockpaperscissors": ("Play Rock, Paper, Scissors.", "/rockpaperscissors", "", EVERYONE, "Pick with the buttons."),
    "quiz":              ("Answer a random trivia question.", "/quiz", "", EVERYONE, ""),
    "trivia":            ("Answer a random trivia question.", "/trivia", "", EVERYONE, ""),
    "wordle":            ("Guess the 5-letter word.", "/wordle", "", EVERYONE, "Send your guesses as normal messages."),
    "word":              ("Guess the 5-letter word.", "/word", "", EVERYONE, "Send your guesses as normal messages."),
    "chess":             ("Challenge someone to chess, played right in the chat.", "/chess [blitz | rapid | unlimited] [@user]", "/chess rapid @friend", EVERYONE_GRP, "Tap a piece, then a highlighted square. Blitz 5+0 · Rapid 10+5 · default 10+0. Leave out @user for an open challenge."),
    "elo":               ("Show a player's chess rating in this group.", "/elo", "", EVERYONE_GRP, "Reply to a player to see theirs. Everyone starts at 1200."),
    "chesstop":          ("Show the top chess ratings of this group.", "/chesstop", "", EVERYONE_GRP, ""),
    "chessleaderboard":  ("Show the top chess ratings of this group.", "/chessleaderboard", "", EVERYONE_GRP, "Same as /chesstop."),
    "uno":               ("Start an UNO game right in the chat.", "/uno", "", EVERYONE_GRP, f"Join, then tap 🃏 Play a card to pick from your hand. Winner gets {config.CURRENCY_SYMBOL}{config.UNO_WIN_REWARD:,}."),
    "unoend":            ("Stop the UNO game running in this group.", "/unoend", "", "Game host & group admins", "No reward is paid for a stopped game."),
    "rob":               ("Try to steal coins from a member.", "/rob <@user>", "/rob @user", EVERYONE_GRP, f"Or reply to them. 60% success; every {config.ROB_COOLDOWN // 60} min, max {config.ROB_DAILY_LIMIT}/day."),
    "kill":              ("Knock a member out of the round for a while.", "/kill <@user>", "/kill @user", EVERYONE_GRP, f"Or reply to them. Every {config.KILL_COOLDOWN // 60} min, max {config.KILL_DAILY_LIMIT}/day. Shielded players are safe."),
    "shield":            ("Shield yourself or a member from /rob and /kill.", "/shield [@user]", "/shield", EVERYONE_GRP, f"Costs {config.CURRENCY_SYMBOL}{config.SHIELD_COST}, lasts {config.SHIELD_DURATION // 60} min, max {config.SHIELD_DAILY_LIMIT}/day."),
    "protection":        ("Shield yourself or a member from /rob and /kill.", "/protection [@user]", "/protection", EVERYONE_GRP, "Same as /shield."),
    "revive":            ("Bring back a knocked-out member.", "/revive [@user]", "/revive @user", EVERYONE_GRP, f"Costs {config.CURRENCY_SYMBOL}{config.REVIVE_COST}. Or reply to them; they get 5 min of protection."),
    "topkill":           ("Show the top killers of this group.", "/topkill", "", EVERYONE_GRP, ""),
    "propose":           ("Propose marriage to a member.", "/propose <@user>", "/propose @user", EVERYONE_GRP, "Or reply to them. Only they can accept."),
    "marriage":          ("Show who you are married to here.", "/marriage", "", EVERYONE_GRP, ""),
    "married":           ("Show who you are married to here.", "/married", "", EVERYONE_GRP, "Same as /marriage."),
    "divorce":           ("End your marriage in this group.", "/divorce", "", EVERYONE_GRP, ""),
    "shippering":        ("Check the love score of two members.", "/shippering", "", EVERYONE_GRP, "Reply to the member you want to ship with."),
    "checkin":           ("Claim your daily check-in coins.", "/checkin", "", EVERYONE_GRP, "Admins must turn on /checkins first."),
    "checkins":          ("Turn daily check-ins on or off.", "/checkins on | off", "/checkins on", ADMINS_GRP, "Send it alone to see the current state."),
    "reactions":         ("Turn AI reactions on or off.", "/reactions on | off", "/reactions on", ADMINS_GRP, "Send it alone to see the current state."),
    "quiet":             ("Make the AI stop replying on its own.", "/quiet", "", ADMINS_GRP, "/ai still works."),
    "chatty":            ("Let the AI join conversations, react and send stickers on its own.", "/chatty", "", ADMINS_GRP, "The bot needs privacy mode off (BotFather) to see every message."),
    "aistatus":          ("Test every AI provider and show why the AI is not answering.", "/aistatus", "", OWNER, ""),
    "aistickerpack":     ("Choose the sticker packs Aqua uses to answer feelings.", "/aistickerpack <pack name | list | remove name>", "/aistickerpack", OWNER, "Or reply to any sticker with /aistickerpack to add its pack."),
    "groupbot":          ("Turn the group AI on or off.", "/groupbot on | off", "/groupbot off", ADMINS_GRP, "Send it alone to see the current state."),
    "groupmode":         ("Set how active the AI is.", "/groupmode quiet | normal | chatty", "/groupmode chatty", ADMINS_GRP, "Send it alone to see the current mode."),
    "social":            ("Switch social features on or off for a group.", "/social <feature> on | off", "/social games off", OWNER, "Features: ai, memory, economy, games."),
    "whisper":           ("Send a private message only the chosen people can open.", f"@{config.BOT_USERNAME} @user <message>", f"@{config.BOT_USERNAME} @sam +2h !burn See you at 8", EVERYONE, "Type it in any chat's message box (inline mode), then tap the result. Options after the @user: +30m / +2h / +1d (expiry) and !burn (each person reads it once). Up to 5 recipients."),

    "dice":              ("Roll a dice.", "/dice", "", EVERYONE, ""),
    "ball":              ("Roll a bowling ball.", "/ball", "", EVERYONE, ""),
    "basket":            ("Shoot a basketball.", "/basket", "", EVERYONE, ""),
    "dart":              ("Throw a dart.", "/dart", "", EVERYONE, ""),
    "football":          ("Kick a football.", "/football", "", EVERYONE, ""),
    "truth":             ("Get a random truth question.", "/truth", "", EVERYONE, ""),
    "dare":              ("Get a random dare.", "/dare", "", EVERYONE, ""),
    "wish":              ("Send a wish.", "/wish", "", EVERYONE, "Reply to someone to wish them."),
    "movie":             ("Search for a movie.", "/movie <name>", "/movie Inception", EVERYONE, ""),
    "meme":              ("Get a random meme.", "/meme", "", EVERYONE, ""),
    "couple":            ("Pick today's couple of the group.", "/couple", "", EVERYONE_GRP, "A new pair is chosen every day."),
    "love":              ("Check love compatibility between two names.", "/love <name 1> <name 2>", "/love Alice Bob", EVERYONE, ""),
    "cute":              ("Rate how cute someone is.", "/cute", "", EVERYONE, "Reply to someone, or use it for yourself."),
    "bored":             ("Get a random idea when you are bored.", "/bored", "", EVERYONE, ""),

    # ───────────── moderation ─────────────
    "ban":           ("Ban a user from the group.", "/ban <@user or id> [reason]", "/ban @spammer Spam", ADMINS_GRP, "Or reply to the user with /ban [reason]."),
    "unban":         ("Unban a user.", "/unban <@user or id>", "/unban @user", ADMINS_GRP, "Or reply to the user."),
    "tban":          ("Ban a user for a limited time.", "/tban <@user> <time> [reason]", "/tban @user 1d Spam", ADMINS_GRP, "Or reply: /tban 1d. Units: s, m, h, d."),
    "dban":          ("Delete a message and ban its sender.", "/dban [reason]", "/dban Spam", ADMINS_GRP, "Reply to the user's message first."),
    "sban":          ("Ban a user silently.", "/sban <@user or id>", "/sban @user", ADMINS_GRP, "Or reply to the user. Your command is deleted."),
    "kick":          ("Remove a user. They can join again.", "/kick <@user or id> [reason]", "/kick @user", ADMINS_GRP, "Or reply to the user."),
    "kickme":        ("Remove yourself from the group.", "/kickme", "", EVERYONE_GRP, ""),
    "mute":          ("Stop a user from sending messages.", "/mute <@user or id> [reason]", "/mute @user Spam", ADMINS_GRP, "Or reply to the user."),
    "unmute":        ("Let a muted user talk again.", "/unmute <@user or id>", "/unmute @user", ADMINS_GRP, "Or reply to the user."),
    "tmute":         ("Mute a user for a limited time.", "/tmute <@user> <time> [reason]", "/tmute @user 10m", ADMINS_GRP, "Or reply: /tmute 10m. Units: s, m, h, d."),
    "warn":          ("Give a user a warning.", "/warn [reason]", "/warn Spamming", ADMINS_GRP, "Reply to the user first. Reaching the limit bans them."),
    "warnings":      ("Show a user's warnings.", "/warnings", "", ADMINS_GRP, "Reply to the user first."),
    "unwarn":        ("Remove one warning from a user.", "/unwarn", "", ADMINS_GRP, "Reply to the user first."),
    "clearwarnings": ("Remove all warnings of a user.", "/clearwarnings", "", ADMINS_GRP, "Reply to the user first."),
    "setwarnlimit":  ("Set how many warnings lead to a ban.", "/setwarnlimit <1-20>", "/setwarnlimit 3", ADMINS_GRP, ""),
    "promote":       ("Make a user an admin.", "/promote <@user> [title]", "/promote @user Helper", ADMINS_GRP, "Or reply to the user."),
    "fullpromote":   ("Make a user an admin with all rights.", "/fullpromote <@user> [title]", "/fullpromote @user", ADMINS_GRP, "Or reply to the user."),
    "demote":        ("Remove a user's admin rights.", "/demote <@user>", "/demote @user", ADMINS_GRP, "Or reply to the admin."),
    "tempadmin":     ("Make a user admin for a limited time.", "/tempadmin <@user> <time>", "/tempadmin @user 1h", ADMINS_GRP, "Or reply: /tempadmin 1h. Units: s, m, h, d."),
    "purge":         ("Delete all messages from the replied one to now.", "/purge", "", ADMINS_GRP, "Reply to the first message to delete."),
    "spurge":        ("Delete messages silently, without a report.", "/spurge", "", ADMINS_GRP, "Reply to the first message to delete."),
    "purgefrom":     ("Delete messages from a starting point to now.", "/purgefrom", "", ADMINS_GRP, "Reply to the first message to delete."),
    "deleteall":     ("Delete every message of one user.", "/deleteall", "", ADMINS_GRP, "Reply to the user first. The bot needs delete rights."),
    "del":           ("Delete one message.", "/del", "", ADMINS_GRP, "Reply to the message first."),
    "pin":           ("Pin a message.", "/pin", "", ADMINS_GRP, "Reply to the message first."),
    "unpin":         ("Unpin a message.", "/unpin", "", ADMINS_GRP, "Reply to the pinned message."),
    "unpinall":      ("Unpin every pinned message.", "/unpinall", "", ADMINS_GRP, "Asks for confirmation."),
    "report":        ("Report a message to the group admins.", "/report [reason]", "/report Spam", EVERYONE_GRP, "Reply to the message first."),
    "zombies":       ("Remove deleted accounts from the group.", "/zombies", "", ADMINS_GRP, "Asks for confirmation."),
    "tagall":        ("Mention every member of the group.", "/tagall [message]", "/tagall Meeting at 8", ADMINS_GRP, ""),
    "muteall":       ("Mute every non-admin member.", "/muteall", "", ADMINS_GRP, "Asks for confirmation."),
    "banall":        ("Ban every non-admin member.", "/banall", "", ADMINS_GRP, "Asks for confirmation. Use with care."),

    # ───────────── group setup ─────────────
    "settings":      ("Open the settings panel of this group.", "/settings", "", ADMINS_GRP, "Opens settings buttons."),
    "groupdata":     ("Show the saved settings of this group.", "/groupdata", "", ADMINS, "Works inside a group."),
    "staff":         ("List the admins of this group.", "/staff", "", EVERYONE_GRP, ""),
    "admins":        ("List the admins of this group.", "/admins", "", EVERYONE_GRP, ""),
    "bots":          ("List the bots in this group.", "/bots", "", EVERYONE_GRP, ""),
    "auth":          ("Let a user control the player without being admin.", "/auth <@user or id>", "/auth @user", ADMINS_GRP, "Or reply to the user."),
    "unauth":        ("Take back a user's player access.", "/unauth <@user or id>", "/unauth @user", ADMINS_GRP, "Or reply to the user."),
    "authlist":      ("Show the authorized users.", "/authlist", "", EVERYONE_GRP, ""),
    "authusers":     ("Show the authorized users.", "/authusers", "", EVERYONE_GRP, ""),
    "rules":         ("Show the group rules.", "/rules", "", EVERYONE_GRP, ""),
    "setrules":      ("Set the group rules.", "/setrules <text>", "/setrules Be kind. No spam.", ADMINS_GRP, "Or reply to a text message."),
    "setwelcome":    ("Set the welcome message for new members.", "/setwelcome <text>", "/setwelcome Hi {name}, welcome to {group}!", ADMINS_GRP, "{name} and {group} are filled in automatically."),
    "setgoodbye":    ("Set the goodbye message for leaving members.", "/setgoodbye <text>", "/setgoodbye Bye {name}!", ADMINS_GRP, "{name} and {group} are filled in automatically."),
    "goodbye":       ("Turn goodbye messages on or off.", "/goodbye on | off", "/goodbye on", ADMINS_GRP, ""),
    "antilink":      ("Delete links sent by members.", "/antilink on | off", "/antilink on", ADMINS_GRP, ""),
    "addbadword":    ("Add a word to the banned-words list.", "/addbadword <word>", "/addbadword spamword", ADMINS_GRP, ""),
    "removebadword": ("Remove a word from the banned-words list.", "/removebadword <word>", "/removebadword spamword", ADMINS_GRP, ""),
    "badwords":      ("Show the banned words.", "/badwords", "", ADMINS_GRP, ""),
    "flood":         ("Turn anti-flood protection on or off.", "/flood on | off", "/flood on", ADMINS_GRP, ""),
    "setfloodlimit": ("Set how many messages count as flooding.", "/setfloodlimit <2-30>", "/setfloodlimit 6", ADMINS_GRP, "Counted per 5 seconds."),
    "lock":          ("Stop members from sending a type of content.", "/lock <type>", "/lock links", ADMINS_GRP, "Types: all, links, media, stickers, gifs, photos, videos, audio, documents."),
    "unlock":        ("Allow a type of content again.", "/unlock <type>", "/unlock links", ADMINS_GRP, "Types: all, links, media, stickers, gifs, photos, videos, audio, documents."),
    "captcha":       ("Ask new members to prove they are human.", "/captcha on | off", "/captcha on", ADMINS_GRP, ""),
    "raidmode":      ("Protect the group from mass joins.", "/raidmode on | off [joins] [seconds]", "/raidmode on 8 20", ADMINS_GRP, "Default trigger: 8 joins in 20 seconds."),
    "raidstatus":    ("Show the raid-protection status.", "/raidstatus", "", ADMINS_GRP, ""),
    "protect":       ("Turn advanced group protection on or off.", "/protect on | off", "/protect on", ADMINS_GRP, ""),
    "cleanup":       ("Delete the bot's recent messages.", "/cleanup <1-100>", "/cleanup 20", ADMINS_GRP, ""),
    "link":          ("Get the invite link of this group.", "/link", "", ADMINS_GRP, "The bot needs the 'invite users' right."),
    "givelink":      ("Get the invite link of this group.", "/givelink", "", ADMINS_GRP, "The bot needs the 'invite users' right."),
    "filter":        ("Save an auto-reply for a keyword.", "/filter <keyword>", "/filter hello", ADMINS_GRP, "Reply to the message you want as the answer."),
    "filters":       ("List the auto-replies of this group.", "/filters", "", EVERYONE_GRP, ""),
    "get":           ("Get a saved note.", "/get <name>", "/get rules", EVERYONE_GRP, ""),
    "save":          ("Save a note.", "/save <name>", "/save rules", ADMINS_GRP, "Reply to the message you want to save."),
    "notes":         ("List the saved notes.", "/notes", "", EVERYONE_GRP, ""),
    "clear":         ("Delete a saved note.", "/clear <name>", "/clear rules", ADMINS_GRP, ""),
    "cancel":        ("Cancel the current step (for example /string).", "/cancel", "", EVERYONE, ""),
    "setphoto":      ("Change the group photo.", "/setphoto", "", ADMINS_GRP, "Reply to a photo first. Needs the 'change info' right."),
    "removephoto":   ("Remove the group photo.", "/removephoto", "", ADMINS_GRP, "Needs the 'change info' right."),
    "settitle":      ("Change the group name.", "/settitle <new name>", "/settitle Aqua Lounge", ADMINS_GRP, "Or reply to a text message."),
    "setdiscription": ("Change the group description.", "/setdiscription <text>", "/setdiscription Music and chill", ADMINS_GRP, "Or reply to a text message."),
    "leavegroup":    ("Make the bot leave this group.", "/leavegroup", "", OWNER, ""),

    # ───────────── owner tools ─────────────
    "badmin":      ("Add a user to the bot's trusted admins.", "/badmin <@user or id>", "/badmin @user", OWNER, "Or reply to the user."),
    "dbadmin":     ("Remove a user from the trusted admins.", "/dbadmin <@user or id>", "/dbadmin @user", OWNER, "Or reply to the user."),
    "rmadmin":     ("Remove a user from the trusted admins.", "/rmadmin <@user or id>", "/rmadmin @user", OWNER, "Or reply to the user."),
    "delalladmin": ("Remove every extra bot admin.", "/delalladmin", "", OWNER, "The owner always stays."),
    "gban":        ("Ban a user from the bot everywhere.", "/gban <@user or id>", "/gban @user", OWNER, "Or reply to the user."),
    "globalban":   ("Ban a user from the bot everywhere.", "/globalban <@user or id>", "/globalban @user", OWNER, "Same as /gban."),
    "ungban":      ("Lift a global ban.", "/ungban <@user or id>", "/ungban @user", OWNER, "Or reply to the user."),
    "gbannedusers": ("List globally banned users.", "/gbannedusers", "", OWNER, ""),
    "gbanlist":    ("List globally banned users.", "/gbanlist", "", OWNER, ""),
    "block":       ("Block a user from using the bot.", "/block <@user or id>", "/block @user", OWNER, "Or reply to the user."),
    "unblock":     ("Unblock a user.", "/unblock <@user or id>", "/unblock @user", OWNER, "Or reply to the user."),
    "blocked":     ("List blocked users.", "/blocked", "", OWNER, ""),
    "blockedusers": ("List blocked users.", "/blockedusers", "", OWNER, ""),
    "blusers":     ("List blocked users.", "/blusers", "", OWNER, ""),
    "blchat":      ("Blacklist a chat so the bot ignores it.", "/blchat <chat id>", "/blchat -1001234567890", OWNER, ""),
    "blchats":     ("List blacklisted chats.", "/blchats", "", OWNER, ""),
    "blacklistedchats": ("List blacklisted chats.", "/blacklistedchats", "", OWNER, ""),
    "unblchat":    ("Remove a chat from the blacklist.", "/unblchat <chat id>", "/unblchat -1001234567890", OWNER, ""),
    "unblacklistchat": ("Remove a chat from the blacklist.", "/unblacklistchat <chat id>", "/unblacklistchat -1001234567890", OWNER, ""),
    "whitelistchat": ("Remove a chat from the blacklist.", "/whitelistchat <chat id>", "/whitelistchat -1001234567890", OWNER, ""),
    "bbcast":      ("Broadcast a message to all served chats.", "/bbcast <message>", "/bbcast Server update tonight", OWNER, "Or reply to the message to broadcast."),
    "post":        ("Publish a post through the bot.", "/post", "", OWNER, "Reply to the message to publish."),
    "backup":      ("Create a bot and database backup.", "/backup", "", OWNER, ""),
    "maintenance": ("Turn maintenance mode on or off.", "/maintenance enable | disable", "/maintenance enable", OWNER, "The bot stops answering normal users."),
    "logger":      ("Turn activity logging on or off.", "/logger enable | disable", "/logger enable", OWNER, ""),
    "logs":        ("Get the bot's log file.", "/logs", "", OWNER, ""),
    "mongochk":    ("Test a MongoDB connection link.", "/mongochk <mongodb url>", "/mongochk mongodb+srv://...", OWNER, "Delete the message afterwards."),
    "reboot":      ("Reset the bot for this group and stop playback.", "/reboot", "", ADMINS_GRP, "Use it if music gets stuck. Clears the queue."),
    "reload":      ("Refresh the admin list of this group.", "/reload", "", EVERYONE_GRP, "Short cooldown between uses."),
    "refresh":     ("Refresh the admin list of this group.", "/refresh", "", EVERYONE_GRP, "Short cooldown between uses."),
    "admincache":  ("Refresh the admin list of this group.", "/admincache", "", EVERYONE_GRP, "Short cooldown between uses."),
    "botschk":     ("Check which bots are in this group.", "/botschk", "", OWNER, "Works inside a group."),
    "audit":       ("Scan the code and recent errors.", "/audit", "", OWNER, ""),
    "repoaudit":   ("Scan the code and recent errors.", "/repoaudit", "", OWNER, "Same as /audit."),
    "errorscan":   ("Scan the code and recent errors.", "/errorscan", "", OWNER, "Same as /audit."),
    "runtimeerrors": ("Show recent runtime errors.", "/runtimeerrors", "", OWNER, ""),
    "recenterrors":  ("Show recent runtime errors.", "/recenterrors", "", OWNER, ""),
    # ───────────── added: previously missing from the catalog ─────────────
    "addemail": ('Link your Puter email for AI coding.', '/addemail <email>', '/addemail you@puter.email', EVERYONE, 'Never share your Puter password or token.'),
    "ask": ('Run an AI coding job (VIP / VIP Pro).', '/ask <what to build or fix>', '/ask Fix the bug in this repo', EVERYONE, 'Reply to a .zip file to work on a whole repo. Needs /vip.'),
    "paid": ('Send your VIP payment proof to the owner.', '/paid <vip|pro> <UTR>', '/paid vip 123456789012', PM, 'Use it after paying from /vip. Owner approval is required.'),
    "cvideo": ('Create an AI video from a prompt.', '/cvideo <prompt>', '/cvideo waves at sunset', EVERYONE, 'Can take a couple of minutes.'),
    "unomap": ('Link a UNO sticker to a card.', '/unomap <color number | wild | wild4 | status>', '/unomap red 5', OWNER, 'Reply to a sticker first.'),
    "kickall": ('Remove every non-admin member.', '/kickall', '', ADMINS_GRP, 'Asks for confirmation. Use with care.'),
    "unbanall": ('Unban every banned member.', '/unbanall', '', ADMINS_GRP, 'Asks for confirmation.'),
    "unmuteall": ('Unmute every muted member.', '/unmuteall', '', ADMINS_GRP, 'Asks for confirmation.'),
    "cutie": ('Show a random "cute" percentage.', '/cutie', '', EVERYONE, 'Reply to a user to rate them instead.'),
    "gay": ('Show a random "gay" percentage.', '/gay', '', EVERYONE, 'Reply to a user to rate them instead.'),
    "lesbian": ('Show a random "lesbian" percentage.', '/lesbian', '', EVERYONE, 'Reply to a user to rate them instead.'),
    "baka": ('Send an anime GIF to call someone a baka.', '/baka', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "bite": ('Send an anime GIF to bite someone.', '/bite', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "blush": ('Send an anime GIF to blush.', '/blush', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "cuddle": ('Send an anime GIF to cuddle someone.', '/cuddle', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "dance": ('Send an anime GIF to dance.', '/dance', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "facepalm": ('Send an anime GIF to facepalm.', '/facepalm', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "feed": ('Send an anime GIF to feed someone.', '/feed', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "happy": ('Send an anime GIF to show you are happy.', '/happy', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "highfive": ('Send an anime GIF to high-five someone.', '/highfive', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "hug": ('Send an anime GIF to hug someone.', '/hug', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "kiss": ('Send an anime GIF to kiss someone.', '/kiss', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "lurk": ('Send an anime GIF to lurk quietly.', '/lurk', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "nod": ('Send an anime GIF to nod.', '/nod', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "nom": ('Send an anime GIF to nom on someone.', '/nom', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "nope": ('Send an anime GIF to say nope.', '/nope', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "pat": ('Send an anime GIF to pat someone.', '/pat', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "peck": ('Send an anime GIF to peck someone.', '/peck', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "poke": ('Send an anime GIF to poke someone.', '/poke', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "punch": ('Send an anime GIF to punch someone.', '/punch', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "shoot": ('Send an anime GIF to shoot someone.', '/shoot', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "shrug": ('Send an anime GIF to shrug.', '/shrug', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "slap": ('Send an anime GIF to slap someone.', '/slap', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "sleep": ('Send an anime GIF to go to sleep.', '/sleep', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "smile": ('Send an anime GIF to smile.', '/smile', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "smug": ('Send an anime GIF to act smug.', '/smug', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "stare": ('Send an anime GIF to stare at someone.', '/stare', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "think": ('Send an anime GIF to think hard.', '/think', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "tickle": ('Send an anime GIF to tickle someone.', '/tickle', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "wave": ('Send an anime GIF to wave.', '/wave', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "wink": ('Send an anime GIF to wink.', '/wink', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "yawn": ('Send an anime GIF to yawn.', '/yawn', '', EVERYONE, 'Reply to a user to aim it at them.'),
    "yeet": ('Send an anime GIF to yeet someone.', '/yeet', '', EVERYONE, 'Reply to a user to aim it at them.'),
}
# fmt: on

# Reaction commands share one card: reply to someone and the bot sends an animation.
REACTIONS = {
    "punch", "slap", "hug", "bite", "kiss", "highfive", "shoot", "dance", "happy", "baka",
    "pat", "nod", "nope", "cuddle", "feed", "blush", "facepalm", "lurk", "nom", "peck",
    "poke", "sleep", "smile", "gay", "lesbian",
    "cutie",
}


def get_help(command: str):
    """Return (what, usage, example, who, tip) for a command. Never raises."""
    if command in COMMAND_HELP:
        return COMMAND_HELP[command]
    if command in REACTIONS:
        return (f"Send a '{command}' animation to someone.", f"/{command}", "", EVERYONE_GRP,
                "Reply to a member to aim it at them.")
    return ("", f"/{command}", "", "", "")
